# Generated by Django 4.2.15 on 2024-09-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_reliefpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReliefPoint',
        ),
    ]
