# Generated by Django 4.2.15 on 2024-09-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_delete_reliefpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='relieflocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relieflocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rescued', 'Rescued')], default='pending', max_length=10),
        ),
    ]
