# Generated by Django 4.2.15 on 2024-11-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_relieflocation_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relieflocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Duyệt'), ('rescued', 'Đã xong')], default='pending', max_length=10),
        ),
    ]
